### ISSUE TITLE
I2C change SDA SCK Pin

### ISSUE THREAD

**Issue by Yalman** [f-secure-foundry/usbarmory#52]
Hello,

i have a oled Display that have the order GND,VCC,SCL,SCA. Is it possible easy to change the SCL and SCA pin?
Maybe like this?
Dynamically Loading Device Tree Overlays into Linux Kernel:
https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/guides/dt-overlays.md.html

Thanks and Regards

**Comment by abarisani** [comment]
On the USB armory Mk I you mean?

**Comment by Yalman** [comment]
yes

**Comment by abarisani** [comment]
You need to experiment by changing this:

https://github.com/inversepath/usbarmory/blob/master/software/kernel_conf/mark-one/imx53-usbarmory-i2c.dts

**Comment by Yalman** [comment]
ok i try that and report the result

**Comment by Yalman** [comment]
There is a solution with i2c bit banging.
llike https://raspberrypi.stackexchange.com/questions/37796/how-to-use-i2c-gpio-with-raspberry-pi/37804
Prerequisite is a kernel with the option CONFIG_I2C_GPIO

more information further
