### ISSUE TITLE
mk2 fw_env.config?

### ISSUE THREAD

**Issue by AmandaCameron** [f-secure-foundry/usbarmory#54]
I'd like to append some additional kernel parameters to my usb armory mk2, and From my limited understanding, this should be possible through using fw_setenv to change the u-boot boot environment, however I'm having a hard time finding the relevant values to plug into fw_env.config

It should be noted, I want to change these settings while booting from the eMMC. [This Group Convo](https://groups.google.com/forum/#!searchin/usbarmory/fw_env%7Csort:date/usbarmory/6o7i8Kbv0bY/p7J_6o1rCwAJ) mentions maybe making the relevant config available on the wiki, but as far as I can tell that's never happen, and the values I found in that convo don't seem to apply to the Mk2 ( At least not when booting off an eMMC )

Any help would be appreciated. :)

**Comment by andrejro** [comment]
Hi,

put the following line in fw_env.config for changing the U-Boot environment for microSD:
`/dev/mmcblk0p1  0x100000 0x2000 0x2000`

put the following line in fw_env.config for changing the U-Boot environment for eMMC:
`/dev/mmcblk1p1  0x100000 0x2000 0x2000`

By default the U-Boot environment is embedded in the U-Boot binary. So first you would need to execute "saveenv" command at the U-Boot prompt. You need access to the serial console for this step.
