### ISSUE TITLE
[Suggestion]: Hardware Rev. Ɣ / Add NFC antenna

### ISSUE THREAD

**Issue by nekrondev** [f-secure-foundry/usbarmory#61]
The ANNA-B112 supports NFC tag TX which can be used as an additional outbound communication instead of BLE.
However there are no patch antennas for NFC found on the board so reading tags via NFC does not work currently.

Would it be possible to include a patch antenna in the next hardware revision?

**Comment by abarisani** [comment]
Unfortunately we are not interested in allowing NFC use and it would be also difficult to find room for an antenna given the size of the board. Sorry.
