### ISSUE TITLE
Flash bootable image to eMMC

### ISSUE THREAD

**Issue by huntergregal** [f-secure-foundry/usbarmory#62]
As the title suggests -

How do I flash a bootable image to the eMMC (no SDCARD). As far as I can tell the docs do not say how to flash the eMMC without first using an sdcard to boot and copy/ ssh into the device.

I'd assume it would be over the USB/Serial protocol like the imx images -- but the documentation does not address bootable images like the debian pre-built.

Perhaps I am just missing the instructions>

Thanks!

**Comment by abarisani** [comment]
Please see [this page](https://github.com/f-secure-foundry/usbarmory/wiki/Boot-Modes-(Mk-II)#flashing-bootable-images-on-externalinternal-media).

Specifically this section:

"The USB armory Mk II itself can be used as a microSD/eMMC reader using [armory-ums](https://github.com/f-secure-foundry/armory-ums)."

Some instructions in [this thread](https://groups.google.com/g/usbarmory/c/Wt_YXTQkI_Q/m/HGTsFPLZAwAJ).

**Comment by huntergregal** [comment]
@abarisani  -- perfect. thanks for the prompt response. those instructions are exactly what i was looking for -- cheers
