### ISSUE TITLE
i2c doesn't seem to work on Mk I

### ISSUE THREAD

**Issue by MonkeysAreEvil** [f-secure-foundry/usbarmory#67]
I have a Mk I and recently started trying to play with the i2c interface. I'm using the debian image (I've tried both 20190403 (mentioned in #48), and 20210907), I update the link in /boot to point to the i2c.dtb, reboot. When I scan with i2cdetect I get

```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

Which doesn't seem right.

I'll try and setup a serial console over the weekend and see if anything interesting happens during boot.

Am I missing something obvious? Is there some trick in bringing up the i2c interface? Could there be a hardware fault?

Any ideas appreciated,
Thanks

**Comment by andrejro** [comment]
@MonkeysAreEvil what i2c slave are you attaching on the bus? Do the i2c device and armory share the same ground line?

**Comment by MonkeysAreEvil** [comment]
Hi, sorry for the late reply it's taken longer than I expected to get back to this project.

I can verify that GPIO works:
- I test by hooking up an LED and confirming that I can switch it on and off (as per the wiki).
- with the default dtb pins 3, 4, & 7 work and pins 5 & 6 don't do anything.
- with the gpio dtb, all pins work.

So loading dtb's is fine and it appears all the pins work on my device.

Switching over to i2c, I have two devices to work with: (1) this [breakout board](https://www.sparkfun.com/products/13601) and (2) this [display](https://www.wiltronics.com.au/product/19519/0-96-inch-128x64-i2c-oled-display-module-arduino-compatible/).

Following the wiki, when I scan for devices, the display doesn't appear, whereas the breakout board does (I haven't further confirmed if the breakout board works yet). So it appears that i2c does work, at least partially; there may be something wrong with my display or a compatibility issue.

Thanks
