### ISSUE TITLE
Power headers silkscreen is inverted

### ISSUE THREAD

**Issue by gsora** [f-secure-foundry/usbarmory#68]
While poking at the power headers on the debug accessory, I noticed that while the silkscreen labels 3.3V and 5V, the resulting voltages are inverted.

![https://raw.githubusercontent.com/wiki/f-secure-foundry/usbarmory/images/armory-mark-two-debug-accessory.png](https://raw.githubusercontent.com/wiki/f-secure-foundry/usbarmory/images/armory-mark-two-debug-accessory.png)

This is also reflected on the PCB schema:

![telegram-cloud-photo-size-4-5836766195288749626-x](https://user-images.githubusercontent.com/145909/143463022-c380ac45-93a2-4f48-8f91-463b272e1382.jpg)

**Comment by abarisani** [comment]
Thanks for spotting this.

I added an errata [here](https://github.com/f-secure-foundry/usbarmory/wiki/Errata-(Mk-II)#errata-incorrect-silkscreen-labels) as well as [here](https://github.com/f-secure-foundry/usbarmory/tree/master/hardware/mark-two-debug-accessory#errata).

I've also bumped the PCB version to 1.1 with the silkscreen fix in [this commit](https://github.com/f-secure-foundry/usbarmory/commit/6653674982c8120f59a49e8f7c9ea5695207171a#diff-5113252a84911026b578c3d067eb2ba9e566405ab5ce7eaed4bf866d233c2627).

We've also warned the current adapter manufacturer to pick up the new PCB revision for next production batches.
