### ISSUE TITLE
README.md typing error

### ISSUE THREAD

**Issue by Yalman** [f-secure-foundry/usbarmory#71]
hi, there is a typing error

habtool \
  -C ${HAB_KEYS}/SRK_1_key.pem \
  -c ${HAB_KEYS}/SRK_1_crt.pem \
  -A $(HAB_KEYS)/CSF_1_key.pem \     <--- $(
  -a ${HAB_KEYS}/CSF_1_crt.pem \
  -B $(HAB_KEYS)/IMG_1_key.pem \      <--- $(
  -b ${HAB_KEYS}/IMG_1_crt.pem \

**Comment by abarisani** [comment]
Which file are you referring to?
